spring:
  application:
    name: review-service

  config:
    activate:
      on-profile: default

  docker:
    compose:
      enabled: false

  main:
    web-application-type: servlet

  datasource:
    url: jdbc:postgresql://localhost:5435/libri-bookShelf
    username: user
    password: "123"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    # ⬇️ ESTA É A CONFIGURAÇÃO CRUCIAL ⬇️
    hostname: localhost                    # Força localhost
    prefer-ip-address: false               # ⬅️ FALSE para usar hostname
    ip-address: 127.0.0.1                  # Define IP explícito
    non-secure-port-enabled: true
    secure-port-enabled: false
    instance-id: ${spring.application.name}:${server.port}

    # Metadata adicional
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
      hostname: localhost
      ip: 127.0.0.1