--
-- PostgreSQL database dump
--

\restrict L1ZBS7D9fCyNzSb75vQ0kkXHWcOlCuX9KdZxhJYogG4UKEC9DUL3gaawg3sfFTc

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: review; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.review (
    id bigint NOT NULL,
    book_note bigint NOT NULL,
    id_book_reviewed bigint NOT NULL,
    id_user_reviewed bigint NOT NULL,
    review character varying(800) NOT NULL,
    review_title character varying(200) NOT NULL
);


ALTER TABLE public.review OWNER TO "user";

--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: review; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.review (id, book_note, id_book_reviewed, id_user_reviewed, review, review_title) FROM stdin;
1	5	30	1	Escrito por Brian Kernighan e Dennis Ritchie (criador da linguagem), este livro é muito mais que um manual técnico - é um marco histórico da computação. A clareza, precisão e elegância com que apresentam a linguagem C estabeleceram um padrão ouro para literatura de programação. Cada capítulo ensina conceitos fundamentais através de exemplos concisos e úteis, culminando no emblemático 'Hello, world!'. Apesar de sua concisão (apenas ~270 páginas), cobre desde sintaxe básica até estruturas de dados avançadas, ponteiros e operações de baixo nível. É notável como um livro de 1978 continua sendo profundamente relevante, formando gerações de programadores e influenciando inúmeras linguagens modernas.	A Bíblia dos Programadores C
2	5	110	1	Publicado em 1898, 'The Turn of the Screw' de Henry James é muito mais do que um simples conto de fantasmas. É um exercício literário magistral em ambiguidade e terror psicológico, uma obra que, como bem notaram críticos e leitores ao longo de mais de um século, se recusa terminantemente a oferecer uma única verdade[citation:3][citation:4].	O Abismo da Ambiguidade -- Um Clássico Assombrador e Insondável
\.


--
-- Name: review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.review_id_seq', 2, true);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict L1ZBS7D9fCyNzSb75vQ0kkXHWcOlCuX9KdZxhJYogG4UKEC9DUL3gaawg3sfFTc

